name: maya
description: " An application to encrypt your data and share it between devices "
version: '0.0.1'

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  openpgp: ^3.7.2
  basic_utils: ^5.7.0
  flutter_secure_storage: ^4.2.1
  tar: ^1.0.4
  aes_crypt_null_safe: ^3.0.0
  flutter_quill: ^9.3.6
  popover: ^0.3.0
  uuid: ^4.3.3
  file_picker: ^8.0.0+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
